Edit <> Adjusted CICD

diff --git a/.github/workflows/CICD.yml b/.github/workflows/CICD.yml
--- a/.github/workflows/CICD.yml
+++ b/.github/workflows/CICD.yml
@@ -83,7 +83,25 @@ jobs:
       - name: Install Make and Docker Compose
         run: |
           sudo apt-get update
-          sudo apt-get install -y make docker-compose
+          sudo apt-get install -y make
+          # Check if Docker Compose is installed
+            if ! command -v docker-compose &> /dev/null
+            then
+              echo "Docker Compose not found. Installing Docker Compose..."
+              sudo curl -L "https://github.com/docker/compose/releases/download/v2.20.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
+              sudo chmod +x /usr/local/bin/docker-compose
+            else
+              echo "Docker Compose is already installed. Skipping installation."
+            fi
+
+            # Verify Docker Compose installation
+            docker-compose --version
+
+            # Optional: Add current user to the docker group (avoid using sudo for Docker commands)
+            sudo usermod -aG docker $USER
+
+            # Refresh group membership
+            newgrp docker
 
       - name: Create .env.develop file
         run: |
